name: Hello GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo "Hello Sebastian, welcome to GitHub Actions!"